image: donhenton/docker-gulp-sass-node:latest

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install
  - gulp build
  - mv dist public
  artifacts:
    paths:
    - public
  only:
    - master
